// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student.Data;

namespace Student.Migrations
{
    [DbContext(typeof(OurDbContext))]
    [Migration("20191118145407_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Student.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourseForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseForeignKey");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Student.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NoteForeignKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteId");

                    b.HasIndex("NoteForeignKey");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Student.Models.StudentInfo", b =>
                {
                    b.Property<int>("StudentInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentInfoForeignKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentInfoId");

                    b.HasIndex("StudentInfoForeignKey");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Student.Models.Course", b =>
                {
                    b.HasOne("Student.Models.StudentInfo", null)
                        .WithMany("Courses")
                        .HasForeignKey("CourseForeignKey");
                });

            modelBuilder.Entity("Student.Models.Note", b =>
                {
                    b.HasOne("Student.Models.StudentInfo", null)
                        .WithMany("Notes")
                        .HasForeignKey("NoteForeignKey");
                });

            modelBuilder.Entity("Student.Models.StudentInfo", b =>
                {
                    b.HasOne("Student.Models.StudentInfo", null)
                        .WithMany("Restrictions")
                        .HasForeignKey("StudentInfoForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
